// Code generated by `yo/srv/codegen_apistuff.go` DO NOT EDIT
package yo

import (
	util "yo/util"
)

type apiPkgInfo util.Void

func (apiPkgInfo) PkgName() string { return "yo" }

var PkgInfo = apiPkgInfo{}
