// Code generated by `yo/srv/codegen_apistuff.go` DO NOT EDIT
package yo

import util "yo/util"
import q "yo/db/query"

type _ = q.F // just in case of no other generated import users
type apiPkgInfo util.Void

func (apiPkgInfo) PkgName() string { return "yo" }

var PkgInfo = apiPkgInfo{}
