// Code generated by `yo/srv/codegen_apistuff.go` DO NOT EDIT
package yodb

import util "yo/util"
import q "yo/db/query"

type _ = q.F // just in case of no other generated import users
type apiPkgInfo util.Void

func (apiPkgInfo) PkgName() string { return "yodb" }

var PkgInfo = apiPkgInfo{}

const ErrQuery_ExpectedOneOrNoneButNotMultipleOfFldOrStrOrBoolOrInt util.Err = "Query_ExpectedOneOrNoneButNotMultipleOfFldOrStrOrBoolOrInt"
const ErrQuery_ExpectedOnlyEitherQueryOrQueryFromButNotBoth util.Err = "Query_ExpectedOnlyEitherQueryOrQueryFromButNotBoth"
const ErrQuery_ExpectedSetOperandForIN util.Err = "Query_ExpectedSetOperandForIN"
const ErrQuery_ExpectedTwoOperandsForAND util.Err = "Query_ExpectedTwoOperandsForAND"
const ErrQuery_ExpectedTwoOperandsForEQ util.Err = "Query_ExpectedTwoOperandsForEQ"
const ErrQuery_ExpectedTwoOperandsForGE util.Err = "Query_ExpectedTwoOperandsForGE"
const ErrQuery_ExpectedTwoOperandsForGT util.Err = "Query_ExpectedTwoOperandsForGT"
const ErrQuery_ExpectedTwoOperandsForIN util.Err = "Query_ExpectedTwoOperandsForIN"
const ErrQuery_ExpectedTwoOperandsForLE util.Err = "Query_ExpectedTwoOperandsForLE"
const ErrQuery_ExpectedTwoOperandsForLT util.Err = "Query_ExpectedTwoOperandsForLT"
const ErrQuery_ExpectedTwoOperandsForNE util.Err = "Query_ExpectedTwoOperandsForNE"
const ErrQuery_ExpectedTwoOperandsForNOT util.Err = "Query_ExpectedTwoOperandsForNOT"
const ErrQuery_ExpectedTwoOperandsForOR util.Err = "Query_ExpectedTwoOperandsForOR"
const ErrDbDelete_ExpectedQueryForDelete util.Err = "DbDelete_ExpectedQueryForDelete"
const ErrDbUpdate_ExpectedChangesForUpdate util.Err = "DbUpdate_ExpectedChangesForUpdate"
const ErrDbUpdate_ExpectedQueryForUpdate util.Err = "DbUpdate_ExpectedQueryForUpdate"
const Err___db_UserAccount_updateOne_ExpectedIdGreater0 util.Err = "___db_UserAccount_updateOne_ExpectedIdGreater0"
const ___db_UserAccount_countMax = q.F("Max")
const ___db_UserAccount_countOrderBy = q.F("OrderBy")
const ___db_UserAccount_countQuery = q.F("Query")
const ___db_UserAccount_countQueryFrom = q.F("QueryFrom")
const ___db_UserAccount_createManyItems = q.F("Items")
const ___db_UserAccount_createOneCreated = q.F("Created")
const ___db_UserAccount_createOneEmailAddr = q.F("EmailAddr")
const ___db_UserAccount_createOneId = q.F("Id")
const ___db_UserAccount_deleteManyMax = q.F("Max")
const ___db_UserAccount_deleteManyOrderBy = q.F("OrderBy")
const ___db_UserAccount_deleteManyQuery = q.F("Query")
const ___db_UserAccount_deleteManyQueryFrom = q.F("QueryFrom")
const ___db_UserAccount_deleteOneId = q.F("Id")
const ___db_UserAccount_findByIdId = q.F("Id")
const ___db_UserAccount_findManyMax = q.F("Max")
const ___db_UserAccount_findManyOrderBy = q.F("OrderBy")
const ___db_UserAccount_findManyQuery = q.F("Query")
const ___db_UserAccount_findManyQueryFrom = q.F("QueryFrom")
const ___db_UserAccount_findOneMax = q.F("Max")
const ___db_UserAccount_findOneOrderBy = q.F("OrderBy")
const ___db_UserAccount_findOneQuery = q.F("Query")
const ___db_UserAccount_findOneQueryFrom = q.F("QueryFrom")
const ___db_UserAccount_updateManyChanges = q.F("Changes")
const ___db_UserAccount_updateManyIncludingEmptyOrMissingFields = q.F("IncludingEmptyOrMissingFields")
const ___db_UserAccount_updateManyMax = q.F("Max")
const ___db_UserAccount_updateManyOrderBy = q.F("OrderBy")
const ___db_UserAccount_updateManyQuery = q.F("Query")
const ___db_UserAccount_updateManyQueryFrom = q.F("QueryFrom")
const ___db_UserAccount_updateOneChanges = q.F("Changes")
const ___db_UserAccount_updateOneId = q.F("Id")
const ___db_UserAccount_updateOneIncludingEmptyOrMissingFields = q.F("IncludingEmptyOrMissingFields")
const ___db_listTablesName = q.F("Name")
