// Code generated by `yo/srv/codegen_apistuff.go` DO NOT EDIT
package yoauth

import reflect "reflect"
import util "yo/util"
import q "yo/db/query"

type _ = q.F // just in case of no other generated import users
type apiPkgInfo util.Void

func (apiPkgInfo) PkgName() string    { return "yoauth" }
func (me apiPkgInfo) PkgPath() string { return reflect.TypeOf(me).PkgPath() }

var PkgInfo = apiPkgInfo{}

const ErrDbUpdate_ExpectedChangesForUpdate util.Err = "DbUpdate_ExpectedChangesForUpdate"
const ErrDbUpdate_ExpectedQueryForUpdate util.Err = "DbUpdate_ExpectedQueryForUpdate"
const Err___admin_authChangePassword_NewPasswordExpectedToDiffer util.Err = "___admin_authChangePassword_NewPasswordExpectedToDiffer"
const Err___admin_authChangePassword_NewPasswordInvalid util.Err = "___admin_authChangePassword_NewPasswordInvalid"
const Err___admin_authChangePassword_NewPasswordTooLong util.Err = "___admin_authChangePassword_NewPasswordTooLong"
const Err___admin_authChangePassword_NewPasswordTooShort util.Err = "___admin_authChangePassword_NewPasswordTooShort"
const Err___admin_authLogin_AccountDoesNotExist util.Err = "___admin_authLogin_AccountDoesNotExist"
const Err___admin_authLogin_EmailInvalid util.Err = "___admin_authLogin_EmailInvalid"
const Err___admin_authLogin_EmailRequiredButMissing util.Err = "___admin_authLogin_EmailRequiredButMissing"
const Err___admin_authLogin_OkButFailedToCreateSignedToken util.Err = "___admin_authLogin_OkButFailedToCreateSignedToken"
const Err___admin_authLogin_WrongPassword util.Err = "___admin_authLogin_WrongPassword"
const Err___admin_authRegister_EmailAddrAlreadyExists util.Err = "___admin_authRegister_EmailAddrAlreadyExists"
const Err___admin_authRegister_EmailInvalid util.Err = "___admin_authRegister_EmailInvalid"
const Err___admin_authRegister_EmailRequiredButMissing util.Err = "___admin_authRegister_EmailRequiredButMissing"
const Err___admin_authRegister_PasswordInvalid util.Err = "___admin_authRegister_PasswordInvalid"
const Err___admin_authRegister_PasswordTooLong util.Err = "___admin_authRegister_PasswordTooLong"
const Err___admin_authRegister_PasswordTooShort util.Err = "___admin_authRegister_PasswordTooShort"
const ___admin_authChangePasswordEmailAddr = q.F("EmailAddr")
const ___admin_authChangePasswordPasswordNewPlain = q.F("PasswordNewPlain")
const ___admin_authChangePasswordPasswordPlain = q.F("PasswordPlain")
const ___admin_authLoginEmailAddr = q.F("EmailAddr")
const ___admin_authLoginPasswordPlain = q.F("PasswordPlain")
const ___admin_authRegisterEmailAddr = q.F("EmailAddr")
const ___admin_authRegisterPasswordPlain = q.F("PasswordPlain")
