// Code generated by `yo/srv/codegen_apistuff.go` DO NOT EDIT
package yoauth

import (
	util "yo/util"
)

type apiPkgInfo util.Void

func (apiPkgInfo) PkgName() string { return "yoauth" }

var PkgInfo = apiPkgInfo{}

const ErrAuthChangePasswordChangesNotStored util.Err = "AuthChangePasswordChangesNotStored"
const ErrAuthChangePasswordForbidden util.Err = "AuthChangePasswordForbidden"
const ErrAuthChangePasswordNewPasswordInvalid util.Err = "AuthChangePasswordNewPasswordInvalid"
const ErrAuthChangePasswordNewPasswordRequiredButMissing util.Err = "AuthChangePasswordNewPasswordRequiredButMissing"
const ErrAuthChangePasswordNewPasswordSameAsOld util.Err = "AuthChangePasswordNewPasswordSameAsOld"
const ErrAuthChangePasswordNewPasswordTooLong util.Err = "AuthChangePasswordNewPasswordTooLong"
const ErrAuthChangePasswordNewPasswordTooShort util.Err = "AuthChangePasswordNewPasswordTooShort"
const ErrAuthLoginAccountDoesNotExist util.Err = "AuthLoginAccountDoesNotExist"
const ErrAuthLoginEmailInvalid util.Err = "AuthLoginEmailInvalid"
const ErrAuthLoginEmailRequiredButMissing util.Err = "AuthLoginEmailRequiredButMissing"
const ErrAuthLoginOkButFailedToCreateSignedToken util.Err = "AuthLoginOkButFailedToCreateSignedToken"
const ErrAuthLoginPasswordRequiredButMissing util.Err = "AuthLoginPasswordRequiredButMissing"
const ErrAuthLoginWrongPassword util.Err = "AuthLoginWrongPassword"
const ErrAuthRegisterEmailAddrAlreadyExists util.Err = "AuthRegisterEmailAddrAlreadyExists"
const ErrAuthRegisterEmailInvalid util.Err = "AuthRegisterEmailInvalid"
const ErrAuthRegisterEmailRequiredButMissing util.Err = "AuthRegisterEmailRequiredButMissing"
const ErrAuthRegisterPasswordInvalid util.Err = "AuthRegisterPasswordInvalid"
const ErrAuthRegisterPasswordRequiredButMissing util.Err = "AuthRegisterPasswordRequiredButMissing"
const ErrAuthRegisterPasswordTooLong util.Err = "AuthRegisterPasswordTooLong"
const ErrAuthRegisterPasswordTooShort util.Err = "AuthRegisterPasswordTooShort"
const ErrAuthRegisterWhileLoggedIn util.Err = "AuthRegisterWhileLoggedIn"
