// Code generated by `yo/srv/codegen_apistuff.go` DO NOT EDIT
package yoauth

import reflect "reflect"
import util "yo/util"
import q "yo/db/query"

type _ = q.F // just in case of no other generated import users
type apiPkgInfo util.Void

func (apiPkgInfo) PkgName() string    { return "yoauth" }
func (me apiPkgInfo) PkgPath() string { return reflect.TypeOf(me).PkgPath() }

var ThisPkg = apiPkgInfo{}

const ErrDbUpdate_ExpectedChangesForUpdate util.Err = "DbUpdate_ExpectedChangesForUpdate"
const ErrDbUpdate_ExpectedQueryForUpdate util.Err = "DbUpdate_ExpectedQueryForUpdate"
const Err___yo_authChangePassword_NewPasswordExpectedToDiffer util.Err = "___yo_authChangePassword_NewPasswordExpectedToDiffer"
const Err___yo_authChangePassword_NewPasswordInvalid util.Err = "___yo_authChangePassword_NewPasswordInvalid"
const Err___yo_authChangePassword_NewPasswordTooLong util.Err = "___yo_authChangePassword_NewPasswordTooLong"
const Err___yo_authChangePassword_NewPasswordTooShort util.Err = "___yo_authChangePassword_NewPasswordTooShort"
const Err___yo_authLogin_AccountDoesNotExist util.Err = "___yo_authLogin_AccountDoesNotExist"
const Err___yo_authLogin_EmailInvalid util.Err = "___yo_authLogin_EmailInvalid"
const Err___yo_authLogin_EmailRequiredButMissing util.Err = "___yo_authLogin_EmailRequiredButMissing"
const Err___yo_authLogin_OkButFailedToCreateSignedToken util.Err = "___yo_authLogin_OkButFailedToCreateSignedToken"
const Err___yo_authLogin_WrongPassword util.Err = "___yo_authLogin_WrongPassword"
const Err___yo_authRegister_EmailAddrAlreadyExists util.Err = "___yo_authRegister_EmailAddrAlreadyExists"
const Err___yo_authRegister_EmailInvalid util.Err = "___yo_authRegister_EmailInvalid"
const Err___yo_authRegister_EmailRequiredButMissing util.Err = "___yo_authRegister_EmailRequiredButMissing"
const Err___yo_authRegister_PasswordInvalid util.Err = "___yo_authRegister_PasswordInvalid"
const Err___yo_authRegister_PasswordTooLong util.Err = "___yo_authRegister_PasswordTooLong"
const Err___yo_authRegister_PasswordTooShort util.Err = "___yo_authRegister_PasswordTooShort"
const ___yo_authChangePasswordEmailAddr = q.F("EmailAddr")
const ___yo_authChangePasswordPasswordNewPlain = q.F("PasswordNewPlain")
const ___yo_authChangePasswordPasswordPlain = q.F("PasswordPlain")
const ___yo_authLoginEmailAddr = q.F("EmailAddr")
const ___yo_authLoginPasswordPlain = q.F("PasswordPlain")
const ___yo_authRegisterEmailAddr = q.F("EmailAddr")
const ___yo_authRegisterPasswordPlain = q.F("PasswordPlain")
